---
- name: Copy the Node Exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart node_exporter
  when:
    - service_mgr | default(ansible_service_mgr) == 'systemd'

- name: create init service unit
  template:
    src: node_exporter.conf.j2
    dest: /etc/init/node_exporter.conf
    owner: root
    group: root
    mode: 0644
  when:
    - service_mgr | default(ansible_service_mgr) == 'upstart'
    - ansible_os_family != "RedHat"
  notify:
    - reinit node exporter
    - restart node_exporter

- name: create sysvinit service unit
  template:
    src: node_exporter.j2
    dest: /etc/init.d/node_exporter
    owner: root
    group: root
    mode: 0755
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "6"
  notify:
    - restart node_exporter

- name: Create textfile collector dir
  file:
    path: "{{ node_exporter_textfile_dir }}"
    state: directory
    owner: "{{ _node_exporter_system_user }}"
    group: "{{ _node_exporter_system_group }}"
    recurse: true
    mode: 0775
  when: node_exporter_textfile_dir | length > 0

- name: Allow Node Exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ node_exporter_web_listen_address.split(':')[-1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"

- meta: flush_handlers

- name: ensure prometheus node exporter service is enabled and started
  service:
    name: node_exporter
    state: started
    enabled: yes
