---
- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: reinit node exporter
  command: initctl reload-configuration
